name: Playwright Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Instala dependências do projeto
      - name: Install Dependencies
        run: npm install

      # Instala navegadores necessários para o Playwright
      - name: Install Playwright Browsers
        run: npx playwright install

      # Executa os testes configurados no Playwright
      - name: Run Tests
        run: npm test

